name: Docker

on:
  workflow_call:
  
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Nome do artefato que foi salvo 
        name: programago

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
      # Username used to log against the Docker registry
        username: daslimait
      # Password or personal access token used to log against the Docker registry
        password: ${{secrets.PASSWORD_DOCKER_HUB}}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        push: true
        # List of tags (nome da imagem deve ser em minusculas)
        tags: daslima/go_ci:${{github.ref_name}}
